export const refs = {
  form: document.querySelector(`.form`),
  input: document.getElementById('search-input'),
  button: document.querySelector(`.search-button`),
  gallery: document.querySelector(`.gallery`),
  buttonLoadMore: document.querySelector(`.load-more`),
  modal: document.querySelector(`.modal`),
  modalContent: document.querySelector(`.modal_data`),
  movieImage: document.querySelector('.movie_image'),
  movieDescr: document.querySelector('.movie_descr'),
  buttonClose: document.querySelector(`.modal_close`),
  body: document.querySelector(`body`),
  content: document.getElementById('content'),
  headerNavLinks: document.querySelectorAll('.nav_item'),
  headerNavButtons: document.querySelector('.nav_list_button'),
  buttonWatched: document.getElementById('watched'),
  buttonQueue: document.getElementById('queue'),
  butttonsLibrary: document.querySelector('.modal_nav'),
  buttonHeaderNav: document.querySelector('.nav_list_button'),
  logo: document.querySelector('.logo'),
  homeBtn: document.getElementById(`home_btn`),
  libraryBtn: document.getElementById(`library_btn`),
  // genresList: document.getElementById(`genres`),
  // galleryCard: document.querySelector('.gallery_card'),
};
