export const refs = {
  form: document.querySelector(`.form`),
  input: document.getElementById('search-input'),
  button: document.querySelector(`.search-button`),
  gallery: document.querySelector(`.gallery`),
  buttonLoadMore: document.querySelector(`.load-more`),
  modal: document.querySelector(`.modal`),
  modalContent: document.querySelector(`.modal_data`),
  movieCard: document.querySelector('.movie_card'),
  movieDescr: document.querySelector('.movie_descr'),
  buttonClose: document.querySelector(`.modal_close`),
  body: document.querySelector(`body`),
  content: document.getElementById('content'),
  headerNavLinks: document.querySelectorAll('.nav_item'),
  headerNavButtons: document.querySelector('.nav_list_button'),
  buttonWatched: document.getElementById('buttonAdd'),
  logo: document.querySelector('.logo'),
  homeBtn: document.getElementById(`home_btn`),
  libraryBtn: document.getElementById(`library_btn`),
};
